### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(DiceRoller)
add_subdirectory(DiceRollerContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    DiceRollerplugin
    DiceRollerContentplugin)